import { Altitude } from "./Altitude";
import { Orientation3 } from "./Orientation3";
import { GeoCoordinate } from "./GeoCoordinate";
import { Serializable } from "./Serializable";
import { Vector2 } from "./Vector2";
import { TypeName } from "./Enums";
import { Datetime } from "./Datetime";
import { Velocity6 } from "./Velocity6";
import { OrientationReferenceSources } from "./OrientationReferenceSources";
import { OrientationReferenceTargets } from "./OrientationReferenceTargets";
import { Quaternion } from "./Quaternion";
import { CameraSpecification } from "..";
export declare class GeoSpatial implements Serializable {
    readonly type = TypeName.GeoSpatial;
    updated: Datetime;
    coordinate: GeoCoordinate;
    altitude: Altitude;
    orientation: Orientation3;
    velocity: Velocity6;
    applyJSON(json: any): void;
    applyVelocity(time: number): void;
    interpolate(spatial: GeoSpatial, referenceSources: OrientationReferenceSources, referenceTargets: OrientationReferenceTargets, interpolate: (start: number, finish: number) => number): GeoSpatial;
    projectCoordinate(time: number): GeoCoordinate;
    projectAltitude(time: number): Altitude;
    projectOrientation(time: number): Orientation3;
    offset(to: GeoSpatial): Vector2;
    distance(to: GeoSpatial): number;
    groundCoordinate(pitch: number, yaw?: number | null, maxPitch?: number): GeoCoordinate;
    groundCoordinates(cameraSpecification: CameraSpecification, pitch: number, yaw?: number | null, maxPitch?: number): GeoCoordinate[];
    groundCoordinateFromQuaternion(quaternion: Quaternion): GeoCoordinate;
}
