import { PlanComponent } from "../component/PlanComponent";
import { Engagement } from "./Engagement";
import { Execution } from "./Execution";
import { Drone } from "./Drone";
import { Descriptors } from "./Descriptors";
import { Serializable } from "./Serializable";
import { TypeName } from "./Enums";
import { Component } from "../component/Component";
import { ComponentExecutionState } from "../component/ComponentExecutionState";
import { Datetime } from "./Datetime";
import { ComponentExecuteContext } from "../component/ComponentExecuteContext";
import { ComponentEstimate } from "../component/ComponentEstimate";
import { ComponentEstimateContext } from "../component/ComponentEstimateContext";
import { Message } from "./Message";
import { Timeline } from "./Timeline";
import { ComponentNodeExecutionState } from "../component/ComponentNodeExecutionState";
import { MessageGroup } from "./MessageGroup";
import { AssetManifest } from "./AssetManifest";
import { Func } from "./Func";
import { GeoSpatial } from "./GeoSpatial";
import { Executable } from "./Executable";
import { ComponentContext } from "../component/ComponentContext";
import { CameraFile } from "./CameraFile";
import { Context } from "./Context";
import { GeoCoordinate } from "./GeoCoordinate";
export declare class Mission extends Executable implements Serializable {
    readonly type = TypeName.Mission;
    descriptors: Descriptors | null;
    func: Func | null;
    plan: PlanComponent;
    execution: Execution;
    applyJSON(json: any): void;
    static createFromComponent(component: Component): Mission;
    get coordinate(): GeoCoordinate;
    get verification(): Mission | null;
    get complete(): boolean;
    get state(): ComponentExecutionState;
    get componentNodeExecutionStates(): ComponentNodeExecutionState[];
    get executingMessageGroups(): MessageGroup[];
    get droneMotionComponentCount(): number;
    get elevationsRequired(): boolean;
    get context(): ComponentContext;
    componentExecuteContext(context: Context, engagement: Engagement): ComponentExecuteContext;
    componentEstimateParams(pathRequired?: boolean, altitudeRequired?: boolean, timeRequired?: boolean, drone?: Drone | null): {
        context: ComponentEstimateContext;
        start: GeoSpatial;
    };
    estimate(altitudeRequired?: boolean, timeRequired?: boolean, drone?: Drone | null): ComponentEstimate;
    engageDisallowedReasons(context: Context): Message[];
    engage(context: Context, datetime?: Datetime | null): Engagement | null;
    execute(context: Context, datetime?: Datetime | null, timeline?: Timeline | null): any;
    get executionDuration(): number;
    addCameraFile(channel: number, cameraFile: CameraFile): void;
    reengagement(drone: Drone): Mission | null;
    get assetManifest(): AssetManifest;
    simulate(metadata: any, progress: (mission: Mission, timeline: Timeline) => boolean): void;
}
