import { ApproachableComponent } from "./ApproachableComponent";
import { Serializable } from "../core/Serializable";
import { Component } from "./Component";
import { TypeName, FacadeCapturePriority, FacadeBoundaryFace, FacadePattern, CameraMode, PathCornering, CameraPhotoMode } from "../core/Enums";
import { CameraSpecification, GroundSampleDistance } from "../core/CameraSpecification";
import { FacadeComponentBoundaryPoint } from "./FacadeComponentBoundaryPoint";
import { Altitude } from "../core/Altitude";
import { Vector2 } from "../core/Vector2";
import { GeoCoordinate } from "../core/GeoCoordinate";
import { Line2 } from "../core/Line2";
import { Path } from "../core/Path";
import { ComponentNode } from "./ComponentNode";
import { Node } from "../core/Node";
import { ComponentEstimateContext } from "./ComponentEstimateContext";
import { GeoSpatial } from "../core/GeoSpatial";
import { ComponentEstimate } from "./ComponentEstimate";
import { Orientation3Optional } from "../core/Orientation3Optional";
import { Dictionary } from "../core/Dictionary";
import { ComponentExecuteContext } from "./ComponentExecuteContext";
import { ComponentExecutionState } from "./ComponentExecutionState";
import { ReferencedAltitude } from "../core/ReferencedAltitude";
import { ComponentContext } from "./ComponentContext";
import { FacadeComponentModel, FacadeComponentModelData, FacadeComponentModelParameters } from "./FacadeComponentModel";
export declare class FacadeComponent extends ApproachableComponent implements Serializable {
    readonly type = TypeName.FacadeComponent;
    initialAltitude: Altitude;
    finalAltitude: Altitude;
    cameraSpecification: CameraSpecification;
    gimbalOrientations: Dictionary<Orientation3Optional>;
    droneOrientation: Orientation3Optional | null;
    cameraMode: CameraMode;
    cameraPhotoMode: CameraPhotoMode;
    capturePriority: FacadeCapturePriority;
    minCaptureInterval: number;
    targetDistance: number;
    sampleDistanceGimbalAngleEnabled: boolean;
    pattern: FacadePattern;
    cornering: PathCornering;
    cornerRadius: number;
    verticalOverlap: number;
    horizontalOverlap: number;
    boundaryFace: FacadeBoundaryFace;
    boundaryPoints: FacadeComponentBoundaryPoint[];
    applyJSON(json: any): void;
    get subtitle(): string;
    verification(context: ComponentContext): Component | null;
    cameraCaptureConfigurationsEnabled(context?: ComponentExecuteContext | null): boolean;
    alignment(context: ComponentContext): {
        droneOrientation: Orientation3Optional | null;
        gimbalOrientations: Dictionary<Orientation3Optional> | null;
    } | null;
    get referenceOffsets(): Vector2[];
    referenceOffsetsHandleCoordinate(context: ComponentContext): GeoCoordinate;
    elevationCoordinates(context: ComponentContext): GeoCoordinate[];
    node(parent?: Node | null): ComponentNode;
    centerCoordinate(context: ComponentContext): GeoCoordinate;
    initialReferencedAltitude(context: ComponentContext): ReferencedAltitude;
    finalReferencedAltitude(context: ComponentContext): ReferencedAltitude;
    get surfaceSampleDistance(): GroundSampleDistance;
    resetApproachDestinationOffset(context: ComponentContext): void;
    reverseBoundaryPoints(context: ComponentContext): void;
    addBoundaryPoint(boundaryPoint: FacadeComponentBoundaryPoint, context?: ComponentContext | null, index?: number | null): FacadeComponentBoundaryPoint;
    get boundaryClosed(): boolean;
    updateBoundaryPointCoordinate(index: number, coordinate: GeoCoordinate, context: ComponentContext): void;
    removeBoundaryPoint(boundaryPoint: FacadeComponentBoundaryPoint, context: ComponentContext): FacadeComponentBoundaryPoint;
    get boundaryPointOffsets(): Vector2[];
    get maxBoundaryPoints(): number;
    get boundarySegments(): Line2[];
    boundaryPointCoordinates(context: ComponentContext): GeoCoordinate[];
    boundaryPointCoordinate(context: ComponentContext, index: number): GeoCoordinate;
    get boundaryFaceOrientation(): number;
    endSpatial(context: ComponentContext): GeoSpatial | null;
    estimate(context: ComponentEstimateContext, start: GeoSpatial): ComponentEstimate;
    cachedData(context: ComponentExecuteContext): FacadeComponentModelData | null;
    engaging(context: ComponentExecuteContext, start: GeoSpatial): void;
    execute(context: ComponentExecuteContext): ComponentExecutionState;
    reengagementDroneSpatial(context: ComponentExecuteContext): GeoSpatial | null;
    paths(context: ComponentContext): Path[] | null;
    get pathCorneringEnabled(): boolean;
    get patternEnabled(): boolean;
    get patternResolved(): FacadePattern;
    private pathsOffsets;
    modelParameters(context: ComponentContext, paths?: Path[] | null): FacadeComponentModelParameters | null;
    model(context: ComponentContext, timeRequired?: boolean): FacadeComponentModel | null;
}
