import { ComponentExecutionState } from "./ComponentExecutionState";
import { ComponentExecuteContext } from "./ComponentExecuteContext";
import { OrbitDirection, TypeName } from "../core/Enums";
import { Vector2 } from "../core/Vector2";
import { Serializable } from "../core/Serializable";
import { Context } from "../core/Context";
import { ComponentEstimate } from "./ComponentEstimate";
import { ApproachableComponent } from "./ApproachableComponent";
import { GeoCoordinate } from "../core/GeoCoordinate";
import { GeoSpatial } from "../core/GeoSpatial";
import { DroneMotionComponentModelSample, DroneMotionComponentModelData, DroneMotionComponentModel } from "./DroneMotionComponent";
import { Orientation3Optional } from "../core/Orientation3Optional";
import { ComponentEstimateContext } from "./ComponentEstimateContext";
import { Dictionary } from "../core/Dictionary";
import { Component } from "./Component";
import { Altitude } from "../core/Altitude";
import { ReferencedAltitude } from "../core/ReferencedAltitude";
export declare class OrbitComponent extends ApproachableComponent implements Serializable {
    readonly type = TypeName.OrbitComponent;
    centerOffset: Vector2;
    direction: OrbitDirection;
    circumference: number;
    finalAltitude: Altitude | null;
    finalRadius: number | null;
    droneOrientation: Orientation3Optional | null;
    gimbalOrientations: Dictionary<Orientation3Optional> | null;
    applyJSON(json: any): void;
    get subtitle(): string;
    verification(context: Context): Component | null;
    get pointsOfInterestEnabled(): boolean;
    get referenceOffsets(): Vector2[];
    get radius(): number;
    set radius(value: number);
    referenceOffsetsHandleCoordinate(context: Context): GeoCoordinate | null;
    elevationCoordinates(context: Context): GeoCoordinate[];
    centerCoordinate(context: Context): GeoCoordinate;
    finalCoordinate(context: Context): GeoCoordinate;
    finalReferencedAltitude(context: Context): ReferencedAltitude | null;
    alignment(context: Context): {
        droneOrientation: Orientation3Optional | null;
        gimbalOrientations: Dictionary<Orientation3Optional> | null;
    } | null;
    estimate(context: ComponentEstimateContext, start: GeoSpatial): ComponentEstimate;
    cachedData(context: ComponentExecuteContext): DroneMotionComponentModelData<DroneMotionComponentModelSample> | null;
    engaging(context: ComponentExecuteContext, estimate: ComponentEstimate): void;
    execute(context: ComponentExecuteContext): ComponentExecutionState;
    reengagementDroneSpatial(context: ComponentExecuteContext): GeoSpatial | null;
    model(context: Context, positionOnly?: boolean, alignmentOrientationOnly?: boolean): DroneMotionComponentModel<DroneMotionComponentModelSample> | null;
}
