import { ComponentExecutionState } from "./ComponentExecutionState";
import { ComponentExecuteContext } from "./ComponentExecuteContext";
import { Vector2 } from "../core/Vector2";
import { Serializable } from "../core/Serializable";
import { Context } from "../core/Context";
import { ComponentEstimate } from "./ComponentEstimate";
import { TypeName, PathCornering } from "../core/Enums";
import { ApproachableComponent } from "./ApproachableComponent";
import { GeoCoordinate } from "../core/GeoCoordinate";
import { PathComponentWaypoint } from "./PathComponentWaypoint";
import { PathComponentMarker } from "./PathComponentMarker";
import { Path } from "../core/Path";
import { ComponentNode } from "./ComponentNode";
import { PointOfInterestReference } from "../core/PointOfInterest";
import { Node } from "../core/Node";
import { PathComponentModelSample, PathComponentModel } from "./PathComponentModel";
import { Orientation3Optional } from "../core/Orientation3Optional";
import { Dictionary } from "../core/Dictionary";
import { GeoSpatial } from "../core/GeoSpatial";
import { DroneMotionComponentModelData } from "./DroneMotionComponent";
import { ComponentEstimateContext } from "./ComponentEstimateContext";
import { Component } from "./Component";
export declare class PathComponent extends ApproachableComponent implements Serializable {
    readonly type = TypeName.PathComponent;
    cornering: PathCornering;
    cornerRadius: number;
    waypoints: PathComponentWaypoint[];
    markers: PathComponentMarker[];
    applyJSON(json: any): void;
    get subtitle(): string;
    verification(context: Context): Component | null;
    get pointsOfInterestEnabled(): boolean;
    get pointsOfInterestReferences(): PointOfInterestReference[];
    get waypointOffsets(): Vector2[];
    get referenceOffsets(): Vector2[];
    referenceOffsetsHandleCoordinate(context: Context): GeoCoordinate;
    elevationCoordinates(context: Context): GeoCoordinate[];
    node(parent?: Node | null): ComponentNode;
    centerCoordinate(context: Context): GeoCoordinate;
    waypointCoordinate(context: Context, index: number): GeoCoordinate;
    waypointCoordinates(context: Context): GeoCoordinate[];
    addWaypoint(waypoint: PathComponentWaypoint, context?: Context | null): PathComponentWaypoint;
    markerCoordinates(context: Context): GeoCoordinate[] | null;
    addMarker(marker: PathComponentMarker): PathComponentMarker;
    orderMarkers(): void;
    path(context: Context): Path | null;
    alignment(context: Context): {
        droneOrientation: Orientation3Optional | null;
        gimbalOrientations: Dictionary<Orientation3Optional> | null;
    } | null;
    estimate(context: ComponentEstimateContext, start: GeoSpatial): ComponentEstimate;
    cachedData(context: ComponentExecuteContext): DroneMotionComponentModelData<PathComponentModelSample> | null;
    engaging(context: ComponentExecuteContext, estimate: ComponentEstimate): void;
    execute(context: ComponentExecuteContext): ComponentExecutionState;
    reengagementDroneSpatial(context: ComponentExecuteContext): GeoSpatial | null;
    model(context: Context, positionOnly?: boolean, alignmentOrientationOnly?: boolean): PathComponentModel | null;
}
